#pragma once

#define NTL_SAY_MESSAGE_RANGE_IN_METER		(60.0f)
#define NTL_SHOUT_MESSAGE_RANGE_IN_METER		(120.0f)


// 캐릭터 대화창 타입
enum eCHAR_DIALOG_TYPE
{
	CHAR_DIALOG_SAY,
	CHAR_DIALOG_SHOUT,
	CHAR_DIALOG_THINK,

	MAX_CHAR_DIALOG_TYPE,
	INVALID_CHAR_DIALOG
};

enum eDBO_CHATTING_TYPE
{
	DBO_CHATTING_TYPE_GENERAL = 0,
	DBO_CHATTING_TYPE_PARTY_NOTICE,
	DBO_CHATTING_TYPE_GUILD_SCRAMBLE_NOTICE,

	DBO_CHATTING_TYPE_COUNT,

	DBO_CHATTING_TYPE_FIRST = DBO_CHATTING_TYPE_GENERAL,
	DBO_CHATTING_TYPE_LAST = DBO_CHATTING_TYPE_COUNT - 1,
};