#include "StdAfx.h"
#include "NtlPacketGU.h"

const char * s_packetName_GU[] =
{
	DECLARE_PACKET_NAME( GU_PONG ),
	DECLARE_PACKET_NAME( GU_SESSION_STATE_WRONG ),
	DECLARE_PACKET_NAME( GU_CHAR_STATE_WRONG ),

	DECLARE_PACKET_NAME( GU_GAME_ENTER_RES ),
	DECLARE_PACKET_NAME( GU_GAME_LEAVE_RES ),
	DECLARE_PACKET_NAME( GU_ENTER_WORLD_RES ),	
	DECLARE_PACKET_NAME( GU_ENTER_WORLD_COMPLETE ),
	DECLARE_PACKET_NAME( GU_AUTH_KEY_FOR_COMMUNITY_SERVER_RES ),

	DECLARE_PACKET_NAME( GU_AVATAR_CHAR_INFO ),
	DECLARE_PACKET_NAME( GU_AVATAR_ITEM_INFO ),
	DECLARE_PACKET_NAME( GU_AVATAR_SKILL_INFO ),
	DECLARE_PACKET_NAME( GU_AVATAR_HTB_INFO ),
	DECLARE_PACKET_NAME( GU_AVATAR_BUFF_INFO ),
	DECLARE_PACKET_NAME( GU_AVATAR_WORLD_INFO ),
	DECLARE_PACKET_NAME( GU_AVATAR_ZONE_INFO ),
	DECLARE_PACKET_NAME( GU_AVATAR_QUEST_COMPLETE_INFO ),	// 퀘스트 완료 정보
	DECLARE_PACKET_NAME( GU_AVATAR_QUEST_PROGRESS_INFO ),	// 퀘스트 진행 정보
	DECLARE_PACKET_NAME( GU_AVATAR_QUEST_INVENTORY_INFO ),	// 퀘스트 인벤 정보
	DECLARE_PACKET_NAME( GU_AVATAR_INFO_END ),
	DECLARE_PACKET_NAME( GU_AVATAR_ATTRIBUTE_UPDATE ),

	DECLARE_PACKET_NAME( GU_OBJECT_CREATE ),
	DECLARE_PACKET_NAME( GU_OBJECT_DESTROY ),

	DECLARE_PACKET_NAME( GU_CHAR_MOVE ),
	DECLARE_PACKET_NAME( GU_CHAR_DEST_MOVE ),
	DECLARE_PACKET_NAME( GU_CHAR_CHANGE_HEADING ),
	DECLARE_PACKET_NAME( GU_CHAR_MOVE_SYNC ),
	DECLARE_PACKET_NAME( GU_CHAR_CHANGE_JUMP_DIRECTION ),
	DECLARE_PACKET_NAME( GU_CHAR_CHANGE_DIRECTION_ON_FLOATING ),
	DECLARE_PACKET_NAME( GU_CHAR_FOLLOW_MOVE ),
	DECLARE_PACKET_NAME( GU_CHAR_JUMP ),
	DECLARE_PACKET_NAME( GU_CHAR_JUMP_END ),
	DECLARE_PACKET_NAME( GU_CHAR_PUSHED_NFY ),
	DECLARE_PACKET_NAME( GU_CHAR_FIGHTMODE ),
	DECLARE_PACKET_NAME( GU_CHAR_BLOCK_MODE_COOL_TIME_NFY ),
	DECLARE_PACKET_NAME( GU_CHAR_SITDOWN ),
	DECLARE_PACKET_NAME( GU_CHAR_STANDUP ),
	DECLARE_PACKET_NAME( GU_CHAR_CAMPING ),
	DECLARE_PACKET_NAME( GU_CHAR_FAINT ),
	DECLARE_PACKET_NAME( GU_CHAR_KNOCKDOWN ),
	DECLARE_PACKET_NAME( GU_CHAR_SLIDING ),
	DECLARE_PACKET_NAME( GU_CHAR_CONVERT_CLASS ),
	DECLARE_PACKET_NAME( GU_CHAR_DIALOG ),
	DECLARE_PACKET_NAME( GU_CHAR_DIRECT_PLAY ),
	DECLARE_PACKET_NAME( GU_CHAR_DIRECT_PLAY_END ),
	DECLARE_PACKET_NAME( GU_CHAR_AWAY_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_MAIL_INFO ),
	DECLARE_PACKET_NAME( GU_CHAR_KEY_INFO ),
	DECLARE_PACKET_NAME( GU_CHAR_RANKBATTLE_SCORE ),
	DECLARE_PACKET_NAME( GU_CHAR_KEY_UPDATE_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_ACTION_ATTACK ),
	DECLARE_PACKET_NAME( GU_CHAR_ACTION_SKILL ),
	DECLARE_PACKET_NAME( GU_CHAR_ACTION_ITEM ),
	DECLARE_PACKET_NAME( GU_CHAR_REVIVAL_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_TELEPORT_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_BIND_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_SERVER_CHANGE_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_CHANNEL_CHANGE_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_EXIT_RES ),
	DECLARE_PACKET_NAME( GU_CHAR_SKILL_RES ),
	DECLARE_PACKET_NAME( GU_GAME_EXIT_RES ),
	DECLARE_PACKET_NAME( GU_GAME_KICK_NFY ),
	DECLARE_PACKET_NAME( GU_EFFECT_AFFECTED ),
	
	DECLARE_PACKET_NAME( GU_SKILL_CASTING_CANCELED_NFY ),
	DECLARE_PACKET_NAME( GU_SKILL_CASTING_DELAYED_NFY ),
	DECLARE_PACKET_NAME( GU_SKILL_AFFECTING_CANCELED_NFY ),
	DECLARE_PACKET_NAME( GU_SKILL_TARGET_LIST_REQ ),
	DECLARE_PACKET_NAME( GU_SKILL_LEARN_RES ),
	DECLARE_PACKET_NAME( GU_SKILL_LEARNED_NFY ),
	DECLARE_PACKET_NAME( GU_SKILL_UPGRADE_RES ),
	DECLARE_PACKET_NAME( GU_SKILL_RP_BONUS_SETTING_RES ),
	DECLARE_PACKET_NAME( GU_SKILL_NOTIFY_EXP ),
	DECLARE_PACKET_NAME( GU_SKILL_AFTEREFFECT_REMAINING_TIME_NFY ),
	DECLARE_PACKET_NAME( GU_SKILL_COOL_TIME_STARTED_NFY ),
	
	DECLARE_PACKET_NAME( GU_HTB_START_RES ),
	DECLARE_PACKET_NAME( GU_HTB_LEARN_RES ),
	DECLARE_PACKET_NAME( GU_HTB_FORWARD_RES ),
	DECLARE_PACKET_NAME( GU_HTB_RP_BALL_USE_RES ),
	DECLARE_PACKET_NAME( GU_HTB_RP_BALL_USED_NFY ),
	DECLARE_PACKET_NAME( GU_HTB_RP_BALL_RESULT_DECIDED_NFY ),

	DECLARE_PACKET_NAME( GU_BUFF_REGISTERED ),
	DECLARE_PACKET_NAME( GU_BUFF_DROPPED ),
	DECLARE_PACKET_NAME( GU_BUFF_REFRESH_ALL ),
	DECLARE_PACKET_NAME( GU_BUFF_DROP_RES ),

	DECLARE_PACKET_NAME( GU_ITEM_CREATE ),
	DECLARE_PACKET_NAME( GU_ITEM_UPDATE ),
	DECLARE_PACKET_NAME( GU_ITEM_MOVE_RES ),
	DECLARE_PACKET_NAME( GU_ITEM_MOVE_STACK_RES ),
	DECLARE_PACKET_NAME( GU_ITEM_DELETE ),
	DECLARE_PACKET_NAME( GU_ITEM_DELETE_RES ),
	DECLARE_PACKET_NAME( GU_ITEM_EQUIP_REPAIR_RES ),
	DECLARE_PACKET_NAME( GU_ITEM_REPAIR_RES ),
	DECLARE_PACKET_NAME( GU_ITEM_USE_RES ),
	DECLARE_PACKET_NAME( GU_ITEM_CASTING_CANCELED ),
	DECLARE_PACKET_NAME( GU_ITEM_CASTING_DELAYED_NFY ),
	DECLARE_PACKET_NAME( GU_ITEM_DUR_DOWN ),
	DECLARE_PACKET_NAME( GU_ITEM_DUR_UPDATE ),
	DECLARE_PACKET_NAME( GU_ITEM_STACK_UPDATE ),
	DECLARE_PACKET_NAME( GU_ITEM_UPGRADE_RES ),
	DECLARE_PACKET_NAME( GU_ITEM_IDENTIFY_RES ),

	DECLARE_PACKET_NAME( GU_ITEM_PICK_RES ),
	DECLARE_PACKET_NAME( GU_ZENNY_PICK_RES ),

	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_STATE ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_ASPECT_STATE ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_CONDITION ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_EXP ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_LEVEL ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_SPEED ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_ATTACK_SPEEDRATE ),
	DECLARE_PACKET_NAME( GU_UPDATE_ITEM_EQUIP ),
	DECLARE_PACKET_NAME( GU_UPDATE_ITEM_DELETED ),
	DECLARE_PACKET_NAME( GU_UPDATE_TARGET_INFO ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_LP ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_EP ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_RP ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_LP_EP ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_ZENNY ),

	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_MUDOSA_POINT ),

	DECLARE_PACKET_NAME( GU_SYSTEM_DISPLAY_TEXT ),
	DECLARE_PACKET_NAME( GU_SYSTEM_DISPLAY_RESULTCODE ),

	DECLARE_PACKET_NAME( GU_SHOP_START_RES ),
	DECLARE_PACKET_NAME( GU_SHOP_BUY_RES ),
	DECLARE_PACKET_NAME( GU_SHOP_SELL_RES ),
	DECLARE_PACKET_NAME( GU_SHOP_END_RES ),
	DECLARE_PACKET_NAME( GU_SHOP_SKILL_BUY_RES ),

	DECLARE_PACKET_NAME( GU_PARTY_CREATE_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_DISBAND_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_DISBANDED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVITE_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVITE_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_RESPONSE_INVITATION_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_JOINED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INFO ),
	DECLARE_PACKET_NAME( GU_PARTY_INVENTORY_INFO ),
	DECLARE_PACKET_NAME( GU_PARTY_OPENED_CHARM_INVENTORY_INFO ),
	DECLARE_PACKET_NAME( GU_PARTY_INVITATION_DECLINED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVITATION_EXPIRED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_LEAVE_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_LEFT_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_KICK_OUT_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_KICKED_OUT_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_CHANGE_LEADER_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_LEADER_CHANGED_NFY ),

	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_LEVELED_UP_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_CLASS_CHANGED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_OPEN_CHARM_SLOT_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_SLOT_OPENED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_CLOSE_CHARM_SLOT_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_SLOT_CLOSED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_REGISTER_VICTIM_ITEM_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_VICTIM_ITEM_REGISTERED_NFY ),
	
	DECLARE_PACKET_NAME( GU_PARTY_UNREGISTER_VICTIM_ITEM_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_VICTIM_ITEM_UNREGISTERED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_REGISTER_VICTIM_ZENNY_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_VICTIM_ZENNY_REGISTERED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_UNREGISTER_VICTIM_ZENNY_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_VICTIM_ZENNY_UNREGISTERED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_DECLARE_ZENNY_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_DECLARED_ZENNY_CHANGED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_ACTIVATION_FAILED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_ACTIVATE_CHARM_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_ACTIVATED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_DEACTIVATE_CHARM_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_DEACTIVATED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_CHANGE_ZENNY_LOOTING_METHOD_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_ZENNY_LOOTING_METHOD_CHANGED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_CHANGE_ITEM_LOOTING_METHOD_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_ITEM_LOOTING_METHOD_CHANGED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_ZENNY_LOOTING_METHOD_UNLOCKED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_ITEM_LOOTING_METHOD_UNLOCKED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_ZENNY_UPDATED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVENTORY_ITEM_ADDED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVENTORY_ITEM_REMOVED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_GAINED_ITEM_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_GAINED_ZENNY_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEST_ZENNY_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEST_ZENNY_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVENTORY_ITEM_WINNER_CHANGED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_MEMBER_LOCATION_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_ITEM_RANK_SET_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_ITEM_RANK_SET_NFY ),

	DECLARE_PACKET_NAME( GU_BANK_START_RES ),
	DECLARE_PACKET_NAME( GU_BANK_MOVE_RES ),
	DECLARE_PACKET_NAME( GU_BANK_MOVE_STACK_RES ),
	DECLARE_PACKET_NAME( GU_BANK_END_RES ),
	DECLARE_PACKET_NAME( GU_BANK_ZENNY_INFO ),	
	DECLARE_PACKET_NAME( GU_BANK_ITEM_INFO ),
	DECLARE_PACKET_NAME( GU_BANK_ZENNY_RES ),
	DECLARE_PACKET_NAME( GU_BANK_BUY_RES ),
	DECLARE_PACKET_NAME( GU_BANK_ITEM_DELETE_RES ),

	DECLARE_PACKET_NAME( GU_SOCIAL_ACTION ),

	DECLARE_PACKET_NAME( GU_SCOUTER_INDICATOR_RES ),
	DECLARE_PACKET_NAME( GU_SCOUTER_PREDICT_RES ),
	DECLARE_PACKET_NAME( GU_SCOUTER_EQUIP_CHECK_RES ),
	DECLARE_PACKET_NAME( GU_SCOUTER_CHIP_REMOVE_ALL_RES ),
	
	DECLARE_PACKET_NAME( GU_TS_CONFIRM_STEP_RES ),
	DECLARE_PACKET_NAME( GU_TS_UPDATE_SYNC_NFY ),
	DECLARE_PACKET_NAME( GU_TS_UPDATE_STATE ),
	DECLARE_PACKET_NAME( GU_TS_UPDATE_EVENT_NFY ),
	DECLARE_PACKET_NAME( GU_TS_EXCUTE_TRIGGER ),
	DECLARE_PACKET_NAME( GU_TS_EXCUTE_TRIGGER_OBJECT_RES ),
	DECLARE_PACKET_NAME( GU_TS_TRIGGER_OBJECT_DIALOG_NFY ),
	DECLARE_PACKET_NAME( GU_TS_PC_DIALOG_NFY ),
	DECLARE_PACKET_NAME( GU_TS_SKIP_CONTAINER ),

	DECLARE_PACKET_NAME( GU_QUEST_ITEM_CREATE_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_ITEM_DELETE_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_ITEM_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_ITEM_MOVE_RES ),
	DECLARE_PACKET_NAME( GU_QUEST_ITEM_DELETE_RES ),
	DECLARE_PACKET_NAME( GU_QUEST_SVREVT_START_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_SVREVT_END_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_SVREVT_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_GIVEUP_RES ),
	DECLARE_PACKET_NAME( GU_QUEST_SHARE_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_RESET_NFY ),
	DECLARE_PACKET_NAME( GU_QUEST_OBJECT_VISIT_RES ),
	DECLARE_PACKET_NAME( GU_QUEST_FORCED_COMPLETION_NFY ),

	DECLARE_PACKET_NAME( GU_FREEBATTLE_CHALLENGE_RES ),	
	DECLARE_PACKET_NAME( GU_FREEBATTLE_ACCEPT_REQ ),	
	DECLARE_PACKET_NAME( GU_FREEBATTLE_CANCEL_NFY ),	
	DECLARE_PACKET_NAME( GU_FREEBATTLE_START_NFY ),		
	DECLARE_PACKET_NAME( GU_FREEBATTLE_OUTSIDE_NFY ),	
	DECLARE_PACKET_NAME( GU_FREEBATTLE_INSIDE_NFY ),	
	DECLARE_PACKET_NAME( GU_FREEBATTLE_END_NFY ),	

	DECLARE_PACKET_NAME( GU_QUICK_SLOT_UPDATE_RES ),	
	DECLARE_PACKET_NAME( GU_QUICK_SLOT_DEL_NFY ),	
	DECLARE_PACKET_NAME( GU_QUICK_SLOT_INFO ),

	DECLARE_PACKET_NAME( GU_PET_CHAR_INFO ),
	DECLARE_PACKET_NAME( GU_PET_SKILL_INFO ),
	DECLARE_PACKET_NAME( GU_PET_INFO_END ),
	DECLARE_PACKET_NAME( GU_PET_DESPAWNED_NFY ),
	DECLARE_PACKET_NAME( GU_PET_DISMISS_PET_RES ),

	DECLARE_PACKET_NAME( GU_ACTION_REPORT_MESSAGE ),
	DECLARE_PACKET_NAME( GU_TRADE_START_NFY ),
	DECLARE_PACKET_NAME( GU_TRADE_START_RES ),
	DECLARE_PACKET_NAME( GU_TRADE_OK_REQ ),
	DECLARE_PACKET_NAME( GU_TRADE_ADD_NFY ),
	DECLARE_PACKET_NAME( GU_TRADE_ADD_RES ),
	DECLARE_PACKET_NAME( GU_TRADE_DEL_NFY ),
	DECLARE_PACKET_NAME( GU_TRADE_DEL_RES ),
	DECLARE_PACKET_NAME( GU_TRADE_MODIFY_NFY ),
	DECLARE_PACKET_NAME( GU_TRADE_MODIFY_RES ),
	DECLARE_PACKET_NAME( GU_TRADE_ZENNY_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_TRADE_ZENNY_UPDATE_RES ),
	DECLARE_PACKET_NAME( GU_TRADE_END_NFY ),
	DECLARE_PACKET_NAME( GU_TRADE_END_RES ),
	DECLARE_PACKET_NAME( GU_TRADE_CANCEL_NFY ),
	DECLARE_PACKET_NAME( GU_TRADE_CANCEL_RES ),
	DECLARE_PACKET_NAME( GU_TRADE_DENY_RES ),

	DECLARE_PACKET_NAME( GU_GUILD_NAME_CHANGED_NFY ),
	DECLARE_PACKET_NAME( GU_GUILD_CREATE_RES ),
	DECLARE_PACKET_NAME( GU_GUILD_INVITE_RES ),

	DECLARE_PACKET_NAME( GU_TOBJECT_UPDATE_STATE ),
	DECLARE_PACKET_NAME( GU_TOBJECT_ACTION_ATTACK ),
	
	DECLARE_PACKET_NAME( GU_TUTORIAL_HINT_UPDATE_RES ),

	DECLARE_PACKET_NAME( GU_TELECAST_MESSAGE_BEG_NFY ),
	DECLARE_PACKET_NAME( GU_TELECAST_MESSAGE_END_NFY ),
	DECLARE_PACKET_NAME( GU_BROAD_MESSAGE_BEG_NFY ),
	DECLARE_PACKET_NAME( GU_BROAD_MESSAGE_END_NFY ),
	DECLARE_PACKET_NAME( GU_MINI_NARRATION_NFY ),

	DECLARE_PACKET_NAME( GU_PROGRESS_MESSAGE_NFY ),
	DECLARE_PACKET_NAME( GU_DIRECTION_INDICATE_NFY ),

	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_LIST_RES ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_INFO_RES ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_JOIN_RES ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_JOIN_NFY ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_LEAVE_RES ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_LEAVE_RES ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_SELECTION_NFY ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_ROOM_TELEPORT_RES ),

	DECLARE_PACKET_NAME( GU_TIMEQUEST_START_NFY ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_START_EXCEPTION_NFY ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_LEAVE_NFY ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_COUNTDOWN_NFY ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_REWARD_NFY ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_INFORMATION_NFY ),

	DECLARE_PACKET_NAME( GU_TIMEQUEST_UPDATE_GAME_STATE ),	
	DECLARE_PACKET_NAME( GU_TIMEQUEST_UPDATE_KILL_COUNT ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_UPDATE_COUPON_COUNT ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_UPDATE_TMQ_POINT ),
	DECLARE_PACKET_NAME( GU_TIMEQUEST_UPDATE_GAME_TIME ),

	DECLARE_PACKET_NAME( GU_RANKBATTLE_INFO_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_JOIN_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_JOIN_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_LEAVE_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_LEAVE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_MATCH_START_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_MATCH_CANCELED_NFY ),

	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_LIST_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_INFO_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_CREATE_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_CREATE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_LEAVE_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_LEAVE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_JOIN_INFO_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_CHALLENGE_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_CHALLENGE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_MATCH_READY_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_MATCH_START_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_MATCH_CANCEL_RES ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_ROOM_MATCH_CANCELED_NFY ),

	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_STATE_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_TEAM_INFO_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_PLAYER_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_KILLSCORE_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_STAGE_FINISH_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_MATCH_FINISH_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_END_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_BATTLE_FORCED_LEAVE_NFY ),
	DECLARE_PACKET_NAME( GU_RANKBATTLE_TOTAL_SCORE_UPDATE_NFY ),

	DECLARE_PACKET_NAME( GU_DRAGONBALL_START_RES ),
	DECLARE_PACKET_NAME( GU_DRAGONBALL_CHECK_RES ),
	DECLARE_PACKET_NAME( GU_DRAGONBALL_REWARD_RES ),
	DECLARE_PACKET_NAME( GU_DRAGONBALL_COLLECT_NFY ),
	DECLARE_PACKET_NAME( GU_DRAGONBALL_SCHEDULE_INFO ),

	DECLARE_PACKET_NAME( GU_PRIVATESHOP_CREATE_RES ),							//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_CREATE_NFY ),							//  [1/31/2008 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_EXIT_RES ),								//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_OPEN_RES ),								//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_OPEN_NFY ),								//  [7/31/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_CLOSE_RES ),							//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_CLOSE_NFY ),							//  [7/31/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_INSERT_RES ),						//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_UPDATE_RES ),						//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_DELETE_RES ),						//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_BUYING_RES ),						//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_BUYING_NFY ),						//  [7/31/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ENTER_RES ),							//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_LEAVE_RES ),							//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_DATA_INFO ),						//  [7/2/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_SELECT_RES ),						//  [7/19/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_SELECT_NFY ),						//  [7/19/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_ITEM_STATE_NFY ),						//  [7/31/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_LEAVE_NFY ),						//  [8/3/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_REQUEST_RES ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_REQUEST_NFY ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_CONSENT_REQ ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_CONSENT_NFY ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_WAITTIMEOUT_NFY ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_PRICEFLUCTUATIONS_RES ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_PRICEFLUCTUATIONS_NFY ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_IMMEDIATE_ITEM_BUYING_RES ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_IMMEDIATE_ITEM_BUYING_NFY ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_WINDOWCLOSE_NFY ),// [2/4/2008 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_CANCEL_RES ),// [10/17/2007 SGpro]
	DECLARE_PACKET_NAME( GU_PRIVATESHOP_BUSINESS_CANCEL_NFY ),// [10/17/2007 SGpro]

	DECLARE_PACKET_NAME( GU_TUTORIAL_WAIT_NFY ),
	DECLARE_PACKET_NAME( GU_TUTORIAL_WAIT_CANCEL_RES ),
	DECLARE_PACKET_NAME( GU_TUTORIAL_PLAY_QUIT_RES ),

	DECLARE_PACKET_NAME( GU_MAIL_START_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_SEND_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_READ_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_RELOAD_NFY ),
	DECLARE_PACKET_NAME( GU_MAIL_DEL_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_RETURN_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_RELOAD_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_LOAD_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_LOAD_DATA ),
	DECLARE_PACKET_NAME( GU_MAIL_LOAD_INFO ),	
	DECLARE_PACKET_NAME( GU_MAIL_ITEM_RECEIVE_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_LOCK_RES ),
	DECLARE_PACKET_NAME( GU_MAIL_CLOSE_NFY ),
	DECLARE_PACKET_NAME( GU_MAIL_MULTI_DEL_RES ),
	
	DECLARE_PACKET_NAME( GU_PORTAL_START_RES ),
	DECLARE_PACKET_NAME( GU_PORTAL_INFO ),	
	DECLARE_PACKET_NAME( GU_PORTAL_ADD_RES ),
	DECLARE_PACKET_NAME( GU_PORTAL_RES ),

	DECLARE_PACKET_NAME( GU_WAR_FOG_INFO ),
	DECLARE_PACKET_NAME( GU_WAR_FOG_UPDATE_RES ),

	DECLARE_PACKET_NAME( GU_MOB_LUCKY_DROP_NFY ),
	DECLARE_PACKET_NAME( GU_ITEM_UPGRADE_ALL_NFY ),

	DECLARE_PACKET_NAME( GU_BOT_BOTCAUTION_NFY ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_REPUTATION ),

	DECLARE_PACKET_NAME( GU_GUILD_FUNCTION_ADD_RES ),
	DECLARE_PACKET_NAME( GU_GUILD_GIVE_ZENNY_RES ),

	DECLARE_PACKET_NAME( GU_GUILD_BANK_START_RES),
	DECLARE_PACKET_NAME( GU_GUILD_BANK_MOVE_RES),
	DECLARE_PACKET_NAME( GU_GUILD_BANK_MOVE_STACK_RES),
	DECLARE_PACKET_NAME( GU_GUILD_BANK_END_RES),
	DECLARE_PACKET_NAME( GU_GUILD_BANK_ZENNY_INFO),
	DECLARE_PACKET_NAME( GU_GUILD_BANK_ITEM_INFO),
	DECLARE_PACKET_NAME( GU_GUILD_BANK_ZENNY_RES),
	DECLARE_PACKET_NAME( GU_GUILD_CREATE_MARK_RES),
	DECLARE_PACKET_NAME( GU_GUILD_CHANGE_MARK_RES),	
	DECLARE_PACKET_NAME( GU_GUILD_MARK_CHANGED_NFY),

	DECLARE_PACKET_NAME( GU_CROSSFIRE_RES ),
	DECLARE_PACKET_NAME( GU_BANK_LOAD_RES ),// [3/11/2008 SGpro]

	DECLARE_PACKET_NAME( GU_GUILD_CHANGE_NAME_RES),	

	DECLARE_PACKET_NAME( GU_PARTY_SHARETARGET_RES ),// [3/28/2008 SGpro]
	DECLARE_PACKET_NAME( GU_PARTY_SHARETARGET_NFY ),// [3/28/2008 SGpro]

	DECLARE_PACKET_NAME( GU_RIDE_ON_BUS_RES ),
	DECLARE_PACKET_NAME( GU_RIDE_OFF_BUS_RES ),

	DECLARE_PACKET_NAME( GU_TRANSFORM_CANCEL_RES ),
	DECLARE_PACKET_NAME( GU_SHOP_ITEM_IDENTIFY_RES ),

	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_STATE_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_TEAM_INFO_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_PLAYER_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_UPDATE_SCORE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_TEAM_SCORE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_SELECTION_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_STAGE_FINISH_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MINORMATCH_MATCH_FINISH_NFY ),

	DECLARE_PACKET_NAME( GU_MATCH_MAJORMATCH_STATE_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MAJORMATCH_TEAM_INFO_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MAJORMATCH_PLAYER_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MAJORMATCH_UPDATE_SCORE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MAJORMATCH_STAGE_FINISH_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_MAJORMATCH_MATCH_FINISH_NFY ),

	DECLARE_PACKET_NAME( GU_MATCH_FINALMATCH_STATE_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_FINALMATCH_TEAM_INFO_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_FINALMATCH_PLAYER_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_FINALMATCH_UPDATE_SCORE_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_FINALMATCH_STAGE_FINISH_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_FINALMATCH_MATCH_FINISH_NFY ),
	DECLARE_PACKET_NAME( GU_MATCH_AWARDING_NFY ),

	DECLARE_PACKET_NAME( GU_SKILL_CONFUSE_TARGET_NFY ),
	DECLARE_PACKET_NAME( GU_SKILL_TERROR_COURSE_CHANGE_NFY ),

	DECLARE_PACKET_NAME( GU_DICE_ROLL_RES ),
	DECLARE_PACKET_NAME( GU_DICE_ROLLED_NFY ),

	DECLARE_PACKET_NAME( GU_BUDOKAI_STATE_INFO_NFY ),						//
	DECLARE_PACKET_NAME( GU_BUDOKAI_UPDATE_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_UPDATE_MATCH_STATE_NFY ),

	DECLARE_PACKET_NAME( GU_BUDOKAI_JOIN_INDIVIDUAL_RES ),					// 개인 등록
	DECLARE_PACKET_NAME( GU_BUDOKAI_LEAVE_INDIVIDUAL_RES ),					// 개인 취소

	DECLARE_PACKET_NAME( GU_BUDOKAI_JOIN_TEAM_INFO_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_JOIN_TEAM_RES ),						// 팀 등록
	DECLARE_PACKET_NAME( GU_BUDOKAI_JOIN_TEAM_NFY ),						// 팀 등록 알림
	DECLARE_PACKET_NAME( GU_BUDOKAI_LEAVE_TEAM_RES ),						// 팀 등록 취소
	DECLARE_PACKET_NAME( GU_BUDOKAI_LEAVE_TEAM_NFY ),						// 팀 등록 취소 알림
	DECLARE_PACKET_NAME( GU_BUDOKAI_LEAVE_TEAM_MEMBER_RES ),				// 팀 멤버 취소
	DECLARE_PACKET_NAME( GU_BUDOKAI_LEAVE_TEAM_MEMBER_NFY ),				// 팀 멤버 취소 알림

	DECLARE_PACKET_NAME( GU_BUDOKAI_JOIN_INFO_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_JOIN_STATE_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_JOIN_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_MUDOSA_INFO_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_MUDOSA_TELEPORT_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_PROGRESS_MESSAGE_NFY ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_SOCIAL_ACTION_NFY ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_PRIZEWINNER_NAME_RES ),
//	DECLARE_PACKET_NAME( GU_BUDOKAI_PRIZEWINNER_TEAM_NAME_RES ),

	DECLARE_PACKET_NAME( GU_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_GM_MATCH_PROGRESS_INFO_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_GM_MATCH_ARENA_ENTER_RES ),
	DECLARE_PACKET_NAME( GU_BUDOKAI_GM_MATCH_ARENA_LEAVE_RES ),

	DECLARE_PACKET_NAME( GU_DISCONNECTED_NFY ),

	DECLARE_PACKET_NAME( GU_BOT_BOTCAUTION_HELPME_NFY ), // [5/27/2008 SGpro]

	DECLARE_PACKET_NAME( GU_SCOUTER_TURN_ON_NFY ),	
	DECLARE_PACKET_NAME( GU_SCOUTER_TURN_OFF_NFY ),
	DECLARE_PACKET_NAME( GU_SCOUTER_BROKEN_NFY ),
	DECLARE_PACKET_NAME( GU_SCOUTER_ITEM_SELL_RES ),
	
	DECLARE_PACKET_NAME( GU_SHOP_EVENTITEM_START_RES ),// [7/11/2008 SGpro]
	DECLARE_PACKET_NAME( GU_SHOP_EVENTITEM_BUY_RES ),// [7/11/2008 SGpro]
	DECLARE_PACKET_NAME( GU_SHOP_EVENTITEM_END_RES ),// [7/11/2008 SGpro]

	DECLARE_PACKET_NAME( GU_ITEM_REPLACE ),// [7/11/2008 SGpro]

	DECLARE_PACKET_NAME( GU_SHOP_GAMBLE_BUY_RES ),// [7/11/2008 SGpro]

	DECLARE_PACKET_NAME( GU_PARTY_DUNGEON_DIFF_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_DUNGEON_DIFF_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_DUNGEON_INIT_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_DUNGEON_INIT_RES ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_SP ),
	DECLARE_PACKET_NAME( GU_SKILL_INIT_RES ),
	DECLARE_PACKET_NAME( GU_SKILL_REMOVE_NFY ), 
	DECLARE_PACKET_NAME( GU_HTB_REMOVE_NFY ),
	DECLARE_PACKET_NAME( GU_CHAR_MARKING_NFY ), // [9/10/2008 SGpro]

	DECLARE_PACKET_NAME( GU_PARTY_CHARM_DICE_START_NFY ),				// 파티 다이스 UI 띄우고 시작하라
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_DICE_ROLLED_NFY ),				// 선택된 다이스 결과 방송
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_DICE_ROLLED_RES ),				// 선택된 다이스 결과 
	DECLARE_PACKET_NAME( GU_PARTY_CHARM_DICE_END_NFY ),					// 파티 다이스 선택시간 완료 및 총결과
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_LOCK_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_LOCK_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_RESET_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_RESET_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_ACCEPTED_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_ACCEPTED_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_GIVE_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_GIVE_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_DICE_START_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_DICE_START_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_DICE_ROLL_RES ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_DICE_ROLL_NFY ),
	DECLARE_PACKET_NAME( GU_PARTY_INVEN_DICE_END_NFY ),

	DECLARE_PACKET_NAME( GU_TELEPORT_PROPOSAL_NFY ),
	DECLARE_PACKET_NAME( GU_TELEPORT_CONFIRM_RES ),
	
	DECLARE_PACKET_NAME( GU_AVATAR_PETITION_INFO ),

	DECLARE_PACKET_NAME( GU_GAME_COMMON_MSG_NFY ),

	DECLARE_PACKET_NAME( GU_CHAR_NICKNAME_CHANGED_NFY ),

	DECLARE_PACKET_NAME( GU_HOIPOIMIX_RECIPE_REG_NFY ),
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_ITEM_CHECK_RES ),
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_ITEM_MAKE_RES ),
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_ITEM_MAKE_EP_RES ),
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_ITEM_RECIPE_INFO ),
	
	DECLARE_PACKET_NAME( GU_DYNAMIC_OBJECT_UPDATE_STATE ),
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_ITEM_MACHINE_MAKE_RES ),
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_ITEM_MACHINE_DEL_RES ),	
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_ITEM_MAKE_EXP_NFY ),

	DECLARE_PACKET_NAME( GU_CHAR_TARGET_LOST_NFY ),
	DECLARE_PACKET_NAME( GU_CHAR_GUARD_CRASHED_NFY ),

	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_RP_BALL ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_RP_BALL_MAX ),

	DECLARE_PACKET_NAME( GU_HOIPOIMIX_JOB_SET_RES ),
	DECLARE_PACKET_NAME( GU_HOIPOIMIX_JOB_RESET_RES ),

	DECLARE_PACKET_NAME( GU_AVATAR_RP_INCREASE_START_NFY ),
	DECLARE_PACKET_NAME( GU_AVATAR_RP_DECREASE_START_NFY ),
	DECLARE_PACKET_NAME( GU_AVATAR_RP_INCREASE_STOP_NFY ),

	DECLARE_PACKET_NAME( GU_HTB_LAST_STEP_CHANGED_NFY ),

	DECLARE_PACKET_NAME( GU_CHAR_CHARGE_CANCELED_NFY ),
	DECLARE_PACKET_NAME( GU_CHAR_REFRESH_LP_EP ),
	DECLARE_PACKET_NAME( GU_CHAR_NONBATTLEACTIONPATTERNSET_UNITIDX_NFY ),

	DECLARE_PACKET_NAME( GU_VEHICLE_START_NFY ),
	DECLARE_PACKET_NAME( GU_VEHICLE_ENGINE_START_RES ),
	DECLARE_PACKET_NAME( GU_VEHICLE_ENGINE_START_NFY ),
	DECLARE_PACKET_NAME( GU_VEHICLE_ENGINE_STOP_RES ),
	DECLARE_PACKET_NAME( GU_VEHICLE_ENGINE_STOP_NFY ),
	DECLARE_PACKET_NAME( GU_VEHICLE_FUEL_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_VEHICLE_END_RES ),
	DECLARE_PACKET_NAME( GU_VEHICLE_END_NFY ),
	DECLARE_PACKET_NAME( GU_VEHICLE_STUNT_NFY ),
/*
	DECLARE_PACKET_NAME( GU_VEHICLE_PASSENGER_GETON_RES ),
	DECLARE_PACKET_NAME( GU_VEHICLE_PASSENGER_GETON_NFY ),
	DECLARE_PACKET_NAME( GU_VEHICLE_ASK_REQ ),
	DECLARE_PACKET_NAME( GU_VEHICLE_PASSENGER_GETOFF_RES ),
	DECLARE_PACKET_NAME( GU_VEHICLE_PASSENGER_GETOFF_NFY ),
*/

	DECLARE_PACKET_NAME( GU_SKILL_PASSIVE_EFFECT_APPLIED_NFY ),
	DECLARE_PACKET_NAME( GU_AVATAR_UPDATED_SKILL_DATA_INFO ),

	DECLARE_PACKET_NAME( GU_MONSTER_TRANSFORMED_NFY ),

	DECLARE_PACKET_NAME( GU_DOJO_CREATE_RES ),
	DECLARE_PACKET_NAME( GU_DOJO_DELETE_RES ),
	DECLARE_PACKET_NAME( GU_DOJO_FUNCTION_ADD_RES ),
	DECLARE_PACKET_NAME( GU_DOJO_BANK_HISTORY_RES ),
	DECLARE_PACKET_NAME( GU_DOGI_CREATE_RES ),
	DECLARE_PACKET_NAME( GU_DOGI_CHANGE_RES ),
	DECLARE_PACKET_NAME( GU_DOGI_UPDATE_NFY ),
	DECLARE_PACKET_NAME( GU_GUILD_DOGI_CREATE_RES ),
	DECLARE_PACKET_NAME( GU_GUILD_DOGI_CHANGE_RES ),

	DECLARE_PACKET_NAME( GU_CHILD_ADULT_SWITCHED_NFY ),
	DECLARE_PACKET_NAME( GU_CHANGE_CLASS_AUTHORITY_CHANGED_NFY ),

	DECLARE_PACKET_NAME( GU_PLAY_BGM ),
	DECLARE_PACKET_NAME( GU_DOJO_MARK_CHANGED_NFY ),
	DECLARE_PACKET_NAME( GU_DOJO_LEVEL_CHANGED_NFY ),

	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_NETP ),

	DECLARE_PACKET_NAME( GU_DOJO_SCRAMBLE_RES ),
	DECLARE_PACKET_NAME( GU_DOJO_SCRAMBLE_RESPONSE_RES ),
	
	DECLARE_PACKET_NAME( GU_NETMARBLEMEMBERIP_NFY ),

	DECLARE_PACKET_NAME( GU_BUS_LOCATION_NFY ),
	DECLARE_PACKET_NAME( GU_BUS_LOCATION_ERASED_NFY ),
	DECLARE_PACKET_NAME( GU_BUS_LOCATION_RESET_ALL_NFY ),

	DECLARE_PACKET_NAME( GU_ITEM_EXPIRED_NFY ),

	DECLARE_PACKET_NAME( GU_SHOP_NETPYITEM_START_RES ),
	DECLARE_PACKET_NAME( GU_SHOP_NETPYITEM_BUY_RES ),
	DECLARE_PACKET_NAME( GU_SHOP_NETPYITEM_END_RES ),

	DECLARE_PACKET_NAME( GU_CHAR_REFRESH_BATTLE_ATTRIBUTE_MODIFIER ),

	DECLARE_PACKET_NAME( GU_CHAR_RANKBATTLE_ALLOW_NFY ),
	DECLARE_PACKET_NAME( GU_CHAR_RANKPOINT_RESET_NFY ),

	DECLARE_PACKET_NAME( GU_DOJO_NPC_INFO_RES ),

	DECLARE_PACKET_NAME( GU_GAMEGUARD_AUTH_ANSWER_REQ ),

	DECLARE_PACKET_NAME( GU_DOJO_SEAL_ATTACK_BEGIN_NFY ),
	DECLARE_PACKET_NAME( GU_DOJO_SEAL_ATTACK_END_NFY ),
	DECLARE_PACKET_NAME( GU_DOJO_SEAL_CURRENT_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_INVENTORY_CAPSULE_UNLOCK_NFY ),

	DECLARE_PACKET_NAME( GU_DOJO_SCRAMBLE_SHIFT_SEAL_STATE_NFY ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_LP_STATUS_NFY ),

	DECLARE_PACKET_NAME( GU_DURATION_ITEM_BUY_RES ),
	DECLARE_PACKET_NAME( GU_DURATION_RENEW_RES ),

	DECLARE_PACKET_NAME( GU_CASHITEM_START_RES ),
	DECLARE_PACKET_NAME( GU_CASHITEM_INFO_NFY ),
	DECLARE_PACKET_NAME( GU_CASHITEM_END_RES ),
	DECLARE_PACKET_NAME( GU_CASHITEM_MOVE_RES ),
	DECLARE_PACKET_NAME( GU_CASHITEM_USE_RES ),
	DECLARE_PACKET_NAME( GU_CASHITEM_ADD_NFY ),
	DECLARE_PACKET_NAME( GU_CASHITEM_DEL_NFY ),
	DECLARE_PACKET_NAME( GU_CASHITEM_HLSHOP_START_RES ),
	DECLARE_PACKET_NAME( GU_CASHITEM_HLSHOP_END_RES ),
	DECLARE_PACKET_NAME( GU_CASHITEM_BUY_RES ),

	DECLARE_PACKET_NAME( GU_BUDOKAI_PRIZEWINNER_TEAM_NAME_RES ),
	DECLARE_PACKET_NAME( GU_GMT_INFO_NFY ),
	DECLARE_PACKET_NAME( GU_GMT_UPDATE_RES ),
	DECLARE_PACKET_NAME( GU_GMT_CHANGED_NFY ),

	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_MAX_LP ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_MAX_EP ),
	DECLARE_PACKET_NAME( GU_UPDATE_CHAR_MAX_RP ),
};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_GU(WORD wOpCode)
{
	if( wOpCode < GU_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > GU_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - GU_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_GU ) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_GU[ nIndex ];
}




