#include "StdAfx.h"
#include "NtlPacketPS.h"


const char * s_packetName_PS[] =
{
	DECLARE_PACKET_NAME( PS_HEARTBEAT ),

	DECLARE_PACKET_NAME( PS_LOGIN_RES ),					// 로그인 요청 응답
	DECLARE_PACKET_NAME( PS_CHANGE_PASSWORD_RES ),			// 패스워드 변경 응답

	DECLARE_PACKET_NAME( PS_SERVERFARM_NAME_RES ),			// 서버군 이름 응답

	DECLARE_PACKET_NAME( PS_SEARCH_PC_DATA_INFO_START ),	// [6/26/2008 SGpro]
	DECLARE_PACKET_NAME( PS_SEARCH_PC_DATA_INFO ),			// [6/26/2008 SGpro]
	DECLARE_PACKET_NAME( PS_SEARCH_PC_DATA_RES ),			// 캐릭터 찾기 응답
	DECLARE_PACKET_NAME( PS_PC_DATA_RES ),					// 캐릭터 정보 응답

	DECLARE_PACKET_NAME( PS_CHARACTER_LOGIN_INFO_RES ),	// 로그인 정보 요청
	DECLARE_PACKET_NAME( PS_CHARACTER_KICK_INFO_RES ),		// 킥 정보 요청
	DECLARE_PACKET_NAME( PS_CHARACTER_KICK_RES ),			// 캐릭터를 킥 시킨다. (제재 사용)
	DECLARE_PACKET_NAME( PS_CHARACTER_CHANGE_NAME_RES ),		// 캐릭터의 이름을 수정
	DECLARE_PACKET_NAME( PS_CHARNAME_MODIFY_GMTOOL_RES ),		// [5/22/2007 SGpro]

	DECLARE_PACKET_NAME( PS_CHAR_CHANGE_BIND_LOCATION_RES ),// 바인드 위치 수정
	DECLARE_PACKET_NAME( PS_CHAR_CHANGE_CUR_LOCATION_RES ),// 현재 위치 수정
	DECLARE_PACKET_NAME( PS_CHAR_SKILL_DELETE_RES ),			// 스킬 삭제
	DECLARE_PACKET_NAME( PS_CHAR_HTBSKILL_DELETE_RES ),		// HTB 스킬 삭제
	DECLARE_PACKET_NAME( PS_CHAR_BUFFSKILL_DELETE_RES ),		// Buff 스킬 삭제

	DECLARE_PACKET_NAME( PS_SKILL_DELETE_RES ),			// 스킬 삭제
	DECLARE_PACKET_NAME( PS_HTB_SKILL_DELETE_RES ),		// HTB 스킬 삭제
	DECLARE_PACKET_NAME( PS_BUFF_DELETE_RES ),				// 버프 삭제

	DECLARE_PACKET_NAME( PS_ITEM_CREATE_RES ),				// 아이템 생성 응답
	DECLARE_PACKET_NAME( PS_ITEM_DELETE_RES ),				// 아이템 삭제 응답
	DECLARE_PACKET_NAME( PS_ITEM_CHANGE_INFO_RES ),			// 아이템 정보 수정

	DECLARE_PACKET_NAME( PS_PUNISHMENT_INFO_START ),		// 제재 정보 시작
	DECLARE_PACKET_NAME( PS_PUNISHMENT_INFO_INFO ),			// 제재 정보 정보
	DECLARE_PACKET_NAME( PS_PUNISHMENT_INFO_RES ),			// 제재 정보 끝
	DECLARE_PACKET_NAME( PS_PUNISHMENT_RES ),				// 제재하기 응답

	DECLARE_PACKET_NAME( PS_REPEAT_NOTICE_LIST_START_NFY ), // 공지 시작 알림.
	DECLARE_PACKET_NAME( PS_REPEAT_NOTICE_INFO ),			// 공지 내용
	DECLARE_PACKET_NAME( PS_REPEAT_NOTICE_LIST_RES ),		// 공지 내용 리스트 전송이 완료됐을 때 보내는 응답
	DECLARE_PACKET_NAME( PS_REPEAT_NOTICE_ADD_RES ),		// 공지 추가
	DECLARE_PACKET_NAME( PS_REPEAT_NOTICE_CHANGE_RES ),	// 공지 변경
	DECLARE_PACKET_NAME( PS_REPEAT_NOTICE_DELETE_RES ),	// 공지 삭제
	DECLARE_PACKET_NAME( PS_REALTIME_NOTICE_RES ),			// 실시간 공지

	DECLARE_PACKET_NAME( PS_SERVER_STATUS_RES ),			// 서버 상태 응답	
	DECLARE_PACKET_NAME( PS_SERVER_CONTROL_TURN_ON_RES ),	// 서버 시작 요청 응답
	DECLARE_PACKET_NAME( PS_SERVER_CONTROL_TURN_OFF_RES ),	// 서버 종료 요청 응답
	DECLARE_PACKET_NAME( PS_SERVER_LOCK_RES ),				// 서버/서버군/서버 채널 잠금 설정 요청 응답
	DECLARE_PACKET_NAME( PS_SERVER_UNLOCK_RES ),			// 서버/서버군/서버 채널 잠금 해제 요청 응답
	DECLARE_PACKET_NAME( PS_SERVER_USER_ALL_KICK_RES ),		// 접속 중인 사용자의 강제 logout 응답
	DECLARE_PACKET_NAME( PS_SERVER_AGENT_PATCH_RES ),		// Server Agent 패치 요청에 대한 응답

	DECLARE_PACKET_NAME( PS_SEARCH_ACCOUNTID_RES ),			// 아이디에 대한 정보를 찾는다

	DECLARE_PACKET_NAME( PS_GM_CREATE_RES ),				// GM 생성 응답
	DECLARE_PACKET_NAME( PS_GM_DELETE_RES ),				// GM 삭제 응답
	DECLARE_PACKET_NAME( PS_GM_CHANGE_INFO_RES ),			// GM 정보 변경
	DECLARE_PACKET_NAME( PS_GM_CHANGE_ACCOUNTID_RES ),		// GM ACCOUNTID 연결 변경
	DECLARE_PACKET_NAME( PS_GM_CHANGE_PASSWORD_RES ),		// GM 패스워드 변경
	DECLARE_PACKET_NAME( PS_GM_LIST_INFO ),				// GM 정보
	DECLARE_PACKET_NAME( PS_GM_LIST_RES ),					// GM 리스트 검색

	DECLARE_PACKET_NAME( PS_GROUP_CREATE_RES ),				// Group 생성
	DECLARE_PACKET_NAME( PS_GROUP_DELETE_RES ),				// Group 삭제
	DECLARE_PACKET_NAME( PS_GROUP_CHANGE_TOOL_AUTHORITY_RES ),	// Group 의 툴 권한 변경
	DECLARE_PACKET_NAME( PS_GROUP_CHANGE_COMMAND_AUTHORITY_RES ),	// Group의 커맨드 권한 변경
	DECLARE_PACKET_NAME( PS_GROUP_CHANGE_LEVEL_RES ),			// Group 레벨 변경
	DECLARE_PACKET_NAME( PS_GROUP_LOAD_TOOL_AUTHORITY_RES ),		// Group Tool Authority 요청 응답  /// 이거 왜 있는겨 -_-
	DECLARE_PACKET_NAME( PS_GROUP_LIST_RES ),					// Group 리스트 요청
	DECLARE_PACKET_NAME( PS_GROUP_CHANGE_ETC_AUTHORITY_RES ),

	DECLARE_PACKET_NAME( PS_FILTERING_LOAD_LIST_START ),		// 리스트 시작
	DECLARE_PACKET_NAME( PS_FILTERING_LOAD_LIST_DATA ),		// 리스트 데이터
	DECLARE_PACKET_NAME( PS_FILTERING_LOAD_LIST_END ),			// 리스트 종료
	DECLARE_PACKET_NAME( PS_FILTERING_ADD_STRING_RES ),		// 문자열 추가
	DECLARE_PACKET_NAME( PS_FILTERING_DELETE_STRING_RES ),		// 문자열 삭제
	DECLARE_PACKET_NAME( PS_FILTERING_FIND_STRING_RES ),		// 문자열 찾기
	DECLARE_PACKET_NAME( PS_FILTERING_CHANGE_STRING_RES ),		// 문자열 수정
	DECLARE_PACKET_NAME( PS_FILTERING_ADD_STRING_PKG_RES ),	// 여러개의 문자열 추가
	DECLARE_PACKET_NAME( PS_FILTERING_CLEAR_RES ),				// 모든 문자열 삭제

	DECLARE_PACKET_NAME( PS_QUEST_ITEM_CREATE_RES ),			// 퀘스트 아이템 생성 [5/17/2007 SGpro]
	DECLARE_PACKET_NAME( PS_QUEST_ITEM_DELETE_RES ),			// 퀘스트 아이템 삭제 [5/17/2007 SGpro]
	DECLARE_PACKET_NAME( PS_QUEST_ITEM_UPDATE_RES ),			// 퀘스트 아이템 수정 [5/17/2007 SGpro]

	DECLARE_PACKET_NAME( PS_PROGRESS_QUEST_DELETE_RES ),		// 진행중인 퀘스트 삭제 [5/17/2007 SGpro]

	DECLARE_PACKET_NAME( PS_SCHEDULE_ADD_RES ),				// 서버 스케쥴 등록
	DECLARE_PACKET_NAME( PS_SCHEDULE_DEL_RES ),
	DECLARE_PACKET_NAME( PS_SCHEDULE_UPDATE_RES ),
	DECLARE_PACKET_NAME( PS_SCHEDULE_LOAD_RES ),			// 서버 스케쥴 로드

	DECLARE_PACKET_NAME( PS_MAIL_LOADINFO_RES ),			// [10/4/2007 SGpro]
	DECLARE_PACKET_NAME( PS_MAIL_LOAD_DATA ),				// [10/8/2007 SGpro]
	DECLARE_PACKET_NAME( PS_MAIL_DEL_RES ),					// [10/4/2007 SGpro]

	DECLARE_PACKET_NAME( PS_ACCOUNTCOMMENTLOAD_RES ),		// [10/11/2007 SGpro]
	DECLARE_PACKET_NAME( PS_ACCOUNTCOMMENTUPDATE_RES ),		// [10/11/2007 SGpro]

	DECLARE_PACKET_NAME( PS_SERVER_GROUP_STATUS_INFO ),		// [11/20/2007 SGpro]
	DECLARE_PACKET_NAME( PS_SERVER_STATUS_INFO ),			// [11/21/2007 SGpro]

	DECLARE_PACKET_NAME( PS_ZENNYUPDATE_RES ),				// [4/18/2008 SGpro]

	DECLARE_PACKET_NAME( PS_GUILD_SEARCH_START ),			// [7/1/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_SEARCH_INFO ),			// [7/1/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_SEARCH_RES ),// [4/22/2008 SGpro]

	DECLARE_PACKET_NAME( PS_GUILD_INFO_START ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_INFO_MEMBER_INFO ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_INFO_ITEM_INFO ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_INFO_RES ),// [4/22/2008 SGpro]
	
	DECLARE_PACKET_NAME( PS_GUILD_INFO_UPDATE_RES ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_MASTER_MODIFY_RES ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_SECONDMASTER_DEPRIVATION_RES ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_SECONDMASTER_APPOINTMENT_RES ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_MEMBER_SECEDE_RES ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_ITEM_DELETE_RES ),// [4/22/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GUILD_ZENNY_MODIFY_RES ),// [4/22/2008 SGpro]
		
	DECLARE_PACKET_NAME( PS_GUILD_CHAR_KICK_RES ),

	DECLARE_PACKET_NAME( PS_CHAR_DUPLICATE_RES ),
	DECLARE_PACKET_NAME( PS_CHAR_RESCUE_RES ),

	DECLARE_PACKET_NAME( PS_PETITION_LIST_START ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_LIST_INFO ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_LIST_RES ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_LIST_NFY ),// [5/7/2008 SGpro]

	DECLARE_PACKET_NAME( PS_PETITION_DATALOAD_START ),// [5/16/2008 SGpro]	
	DECLARE_PACKET_NAME( PS_PETITION_DATALOAD_COUNSEL_INFO ),// [5/16/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_DATALOAD_LOG_INFO),// [5/16/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_DATALOAD_RES ),// [5/7/2008 SGpro]

	DECLARE_PACKET_NAME( PS_PETITION_GM_INSERT_RES ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_START_RES ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_INIT_RES ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_RESERVE_RES ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_FINISH_RES ),// [5/7/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_CHANGECATEGORY_RES ),// [5/8/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_GM_CHATTING_START_RES ),// [5/8/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_GM_CHATTING_END_RES ),// [5/8/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_SEARCH_RES ), // [5/15/2008 SGpro]
	DECLARE_PACKET_NAME( PS_PETITION_CHAT_START_RES ), // [ by sooshia 2008-10-15 ]
	DECLARE_PACKET_NAME( PS_PETITION_CHAT_GM_SAY_RES ), // [ by sooshia 2008-10-16 ]
	DECLARE_PACKET_NAME( PS_PETITION_CHAT_USER_SAY_NFY ), // [ by sooshia 2008-10-16 ]
	DECLARE_PACKET_NAME( PS_PETITION_CHAT_USER_END_NFY ), // [ by sooshia 2008-10-18 ]

	DECLARE_PACKET_NAME( PS_CHANGEHONOR_RES ),// [6/23/2008 SGpro]
	DECLARE_PACKET_NAME( PS_CHARACTERDELETE_RES ),// [6/26/2008 SGpro]
	DECLARE_PACKET_NAME( PS_CHARACTERRESCUE_RES ),// [6/26/2008 SGpro]
	DECLARE_PACKET_NAME( PS_GM_SERVER_COMMAND_RES ),// [6/30/2008 SGpro]
	DECLARE_PACKET_NAME( PS_CHANGEMUDOSA_RES ), // [ by sooshia 2008-8-6 ]
	DECLARE_PACKET_NAME( PS_CHANGERANKPOINT_RES ), // [ by sooshia 2008-08-07 ]

	DECLARE_PACKET_NAME( PS_SERVER_COMMAND_START ),
	DECLARE_PACKET_NAME( PS_SERVER_COMMAND_INFO ),
	DECLARE_PACKET_NAME( PS_SERVER_COMMAND_END ),

	DECLARE_PACKET_NAME( PS_PLAYER_ENTER_NFY ),
	DECLARE_PACKET_NAME( PS_PLAYER_LEAVE_NFY ),
	DECLARE_PACKET_NAME( PS_CHARACTER_WATCH_RES ),
	DECLARE_PACKET_NAME( PS_SAME_USER_LOGIN_NFY ),
	DECLARE_PACKET_NAME( PS_MASTERSERVER_DISCONNECTED_NFY ),
	DECLARE_PACKET_NAME( PS_MASTERSERVER_CONNECTED_NFY ),
	DECLARE_PACKET_NAME( PS_CHARACTER_INIT_SKILL_RES ),
	DECLARE_PACKET_NAME( PS_GAME_LOG_LIST_START ),
	DECLARE_PACKET_NAME( PS_GAME_LOG_LIST_DATA_READY_REQ ),
	DECLARE_PACKET_NAME( PS_GAME_LOG_LIST_DATA ),
	DECLARE_PACKET_NAME( PS_GAME_LOG_LIST_RES ),
	DECLARE_PACKET_NAME( PS_SERVER_STATUS_LOCALSETTING_INFO_RES ),
	DECLARE_PACKET_NAME( PS_SERVER_STATUS_LOCALSETTING_EDIT_RES ),
	DECLARE_PACKET_NAME( PS_CHARACTER_CHANGE_SP_RES ),
	DECLARE_PACKET_NAME( PS_CHARACTER_SKILL_ADD_RES ),
	DECLARE_PACKET_NAME( PS_CHARACTER_HTB_ADD_RES ),
	DECLARE_PACKET_NAME( PS_CHARACTER_CHANGE_EXP_RES ),
	DECLARE_PACKET_NAME( PS_CHARACTER_CHANGE_LEVEL_RES ),
	DECLARE_PACKET_NAME( PS_MULTI_MAIL_HISTORY_START_NFY ),
	DECLARE_PACKET_NAME( PS_MULTI_MAIL_HISTORY_READY_REQ ),
	DECLARE_PACKET_NAME( PS_MULTI_MAIL_HISTORY_DATA_NFY ),
	DECLARE_PACKET_NAME( PS_MULTI_MAIL_HISTORY_RES ),
	DECLARE_PACKET_NAME( PS_MULTI_MAIL_SEND_RES ),

	DECLARE_PACKET_NAME( PS_GM_COMMAND_LOG_LIST_START ), // itzrnb
	DECLARE_PACKET_NAME( PS_GM_COMMAND_LOG_LIST_DATA_READY_REQ ),
	DECLARE_PACKET_NAME( PS_GM_COMMAND_LOG_LIST_DATA ),
	DECLARE_PACKET_NAME( PS_GM_COMMAND_LOG_LIST_RES ),

	DECLARE_PACKET_NAME( PS_IP_MANAGE_SAMEIP_SEARCH_START ),
	DECLARE_PACKET_NAME( PS_IP_MANAGE_SAMEIP_SEARCH_DATA ),
	DECLARE_PACKET_NAME( PS_IP_MANAGE_SAMEIP_SEARCH_RES ),

	DECLARE_PACKET_NAME( PS_IP_MANAGE_SAMEIP_USER_LIST_START ),
	DECLARE_PACKET_NAME( PS_IP_MANAGE_SAMEIP_USER_LIST_DATA ),
	DECLARE_PACKET_NAME( PS_IP_MANAGE_SAMEIP_USER_LIST_RES ),

	DECLARE_PACKET_NAME( PS_IP_MANAGE_INFO_SEARCH_START ),
	DECLARE_PACKET_NAME( PS_IP_MANAGE_INFO_SEARCH_DATA ),
	DECLARE_PACKET_NAME( PS_IP_MANAGE_INFO_SEARCH_RES ),

	DECLARE_PACKET_NAME( PS_IP_MANAGE_INFO_EDIT_RES ),

	DECLARE_PACKET_NAME( PS_GM_LOG_LIST_START ),
	DECLARE_PACKET_NAME( PS_GM_LOG_LIST_DATA_READY_REQ ),
	DECLARE_PACKET_NAME( PS_GM_LOG_LIST_DATA ),
	DECLARE_PACKET_NAME( PS_GM_LOG_LIST_RES ),

};

//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_PS(WORD wOpCode)
{
	if( wOpCode < PS_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > PS_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - PS_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_PS) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_PS[ nIndex ];
}