#pragma once

#include "NtlSharedType.h"
#include "NtlVector.h"


// 스킬 관련 enumeration
enum eSKILL_CLASS
{
	SKILL_CLASS_PASSIVE = 0,
	SKILL_CLASS_ACTIVE,
	SKILL_CLASS_HTB,

	SKILL_CLASS_UNKNOWN = 0xFFui8,

	SKILL_CLASS_FIRST = SKILL_CLASS_PASSIVE,
	SKILL_CLASS_LAST = SKILL_CLASS_HTB
};


// 스킬 종류
enum eSKILL_TYPE
{
	SKILL_TYPE_NONE = 0,
	SKILL_TYPE_PHYSICAL,
	SKILL_TYPE_ENERGY,
	SKILL_TYPE_STATE,

	SKILL_TYPE_FIRST = SKILL_TYPE_NONE,
	SKILL_TYPE_LAST = SKILL_TYPE_STATE,

	SKILL_TYPE_COUNT = SKILL_TYPE_LAST - SKILL_TYPE_FIRST + 1
};


// 스킬 타입
enum eSKILL_ACTIVE_TYPE
{
	SKILL_ACTIVE_TYPE_DD, // Direct Damage ( LP 감소 )
	SKILL_ACTIVE_TYPE_DOT, // Damage Over Time
	SKILL_ACTIVE_TYPE_DH, // Direct Heal
	SKILL_ACTIVE_TYPE_HOT, // Heal Over Time
	SKILL_ACTIVE_TYPE_DB, // Direct Bless ( 독등의 이상 치료, 텔레포트, ... )
	SKILL_ACTIVE_TYPE_BB, // Bless Buff
	SKILL_ACTIVE_TYPE_DC, // Direct Curse ( EP/RP등 감소, ... )
	SKILL_ACTIVE_TYPE_CB, // Curse Buff

	SKILL_ACTIVE_TYPE_UNKNOWN				= 0xFF,

	SKILL_ACTIVE_TYPE_FIRST = SKILL_ACTIVE_TYPE_DD,
	SKILL_ACTIVE_TYPE_LAST = SKILL_ACTIVE_TYPE_CB
};

enum eDBO_SKILL_APPOINT_TARGET
{
	DBO_SKILL_APPOINT_TARGET_SELF = 0,
	DBO_SKILL_APPOINT_TARGET_TARGET,
	DBO_SKILL_APPOINT_TARGET_POINT,

	DBO_SKILL_APPOINT_TARGET_COUNT,

	DBO_SKILL_APPOINT_TARGET_UNKNOWN = 0xFF,

	DBO_SKILL_APPOINT_TARGET_FIRST = DBO_SKILL_APPOINT_TARGET_SELF,
	DBO_SKILL_APPOINT_TARGET_LAST = DBO_SKILL_APPOINT_TARGET_COUNT - 1
};

enum eDBO_SKILL_APPLY_TARGET
{
	DBO_SKILL_APPLY_TARGET_SELF = 0,
	DBO_SKILL_APPLY_TARGET_ENEMY,
	DBO_SKILL_APPLY_TARGET_ALLIANCE,
	DBO_SKILL_APPLY_TARGET_PARTY,
	DBO_SKILL_APPLY_TARGET_MOB_PARTY,
	DBO_SKILL_APPLY_TARGET_ANY,

	DBO_SKILL_APPLY_TARGET_COUNT,

	DBO_SKILL_APPLY_TARGET_UNKNOWN = 0xFF,

	DBO_SKILL_APPLY_TARGET_FIRST = DBO_SKILL_APPLY_TARGET_SELF,
	DBO_SKILL_APPLY_TARGET_LAST = DBO_SKILL_APPLY_TARGET_COUNT - 1
};

enum eDBO_SKILL_APPLY_RANGE
{
	DBO_SKILL_APPLY_RANGE_SINGLE = 0,
	DBO_SKILL_APPLY_RANGE_CIRCLE,
	DBO_SKILL_APPLY_RANGE_RECTANGLE,
	DBO_SKILL_APPLY_RANGE_FORWARD,

	DBO_SKILL_APPLY_RANGE_UNKNOWN = 0xFF,

	DBO_SKILL_APPLY_RANGE_FIRST = DBO_SKILL_APPLY_RANGE_SINGLE,
	DBO_SKILL_APPLY_RANGE_LAST = DBO_SKILL_APPLY_RANGE_FORWARD
};

enum eDBO_SYSTEM_EFFECT_RESULT_TYPE
{
	DBO_SYSTEM_EFFECT_RESULT_TYPE_GENERAL = 0,
	DBO_SYSTEM_EFFECT_RESULT_TYPE_DH_HOT,
	DBO_SYSTEM_EFFECT_RESULT_TYPE_DD_DOT,
	DBO_SYSTEM_EFFECT_RESULT_TYPE_LP_EP_STEAL,

	DBO_SYSTEM_EFFECT_RESULT_TYPE_COUNT,

	DBO_SYSTEM_EFFECT_RESULT_TYPE_UNKNOWN = 0xFFui8,

	DBO_SYSTEM_EFFECT_RESULT_TYPE_FIRST = DBO_SYSTEM_EFFECT_RESULT_TYPE_GENERAL,
	DBO_SYSTEM_EFFECT_RESULT_TYPE_LAST = DBO_SYSTEM_EFFECT_RESULT_TYPE_COUNT - 1
};

// WARNING :
// You can add a new RP bonus type but MUST NOT REMOVE one. These index numbers are synchronized with DB.
// RP 보너스 타입을 추가할 수는 있지만 삭제해서는 안 됩니다. 인덱스 번호들이 DB와 동기화되어 있습니다.
// by YOSHIKI(2007-11-26)
enum eDBO_RP_BONUS_TYPE
{
	DBO_RP_BONUS_TYPE_KNOCKDOWN = 0,
	DBO_RP_BONUS_TYPE_RESULT_PLUS,
	DBO_RP_BONUS_TYPE_EP_MINUS,					// PERCENT
	DBO_RP_BONUS_TYPE_KEEP_TIME_PLUS,			// ABSOLUTE
	DBO_RP_BONUS_TYPE_CASTING_TIME_MINUS,		// ABSOLUTE
	DBO_RP_BONUS_TYPE_COOL_TIME_MINUS,			// ABSOLUTE
	DBO_RP_BONUS_TYPE_GUARD_CRASH,

	DBO_RP_BONUS_TYPE_COUNT,
	DBO_RP_BONUS_TYPE_INVALID = 0xFFui8,

	DBO_RP_BONUS_TYPE_FIRST = DBO_RP_BONUS_TYPE_KNOCKDOWN,
	DBO_RP_BONUS_TYPE_LAST = DBO_RP_BONUS_TYPE_COUNT - 1,
};

//2009년 1월 21일 DBO_BLOCK_MODE_TYPE을 DBO_GUARD_TYPE으로 변경. (승원)
enum eDBO_GUARD_TYPE
{
	DBO_GUARD_TYPE_DEFENCE = 0,
	DBO_GUARD_TYPE_DAMAGE_SKILL,
	DBO_GUARD_TYPE_CURSE_SKILL,
	DBO_GUARD_TYPE_KNOCKDOWN,
	DBO_GUARD_TYPE_HTB,

	DBO_GUARD_TYPE_COUNT,
	DBO_GUARD_TYPE_INVALID = 0xFFui8,

	DBO_GUARD_TYPE_FIRST = DBO_GUARD_TYPE_DEFENCE,
	DBO_GUARD_TYPE_LAST  = DBO_GUARD_TYPE_COUNT - 1
};

enum eDBO_STUN_TYPE
{
	DBO_STUN_TYPE_GENERAL = 0,
	DBO_STUN_TYPE_FROZEN,
	DBO_STUN_TYPE_TIED,
	DBO_STUN_TYPE_STONE,
	DBO_STUN_TYPE_CANDY,

	DBO_STUN_TYPE_COUNT,
	DBO_STUN_TYPE_INVALID = 0xFFui8,

	DBO_STUN_TYPE_FIRST = DBO_STUN_TYPE_GENERAL,
	DBO_STUN_TYPE_LAST = DBO_STUN_TYPE_COUNT - 1
};

enum eDBO_SKILL_PASSIVE_EFFECT
{
	DBO_SKILL_PASSIVE_EFFECT_CASTING_TIME_DOWN = 0,
	DBO_SKILL_PASSIVE_EFFECT_COOL_TIME_DOWN,
	DBO_SKILL_PASSIVE_EFFECT_SYSTEM_EFFECT_VALUE_UP,
	DBO_SKILL_PASSIVE_EFFECT_KEEP_TIME_UP,
	DBO_SKILL_PASSIVE_EFFECT_REQUIRED_EP_DOWN,
	DBO_SKILL_PASSIVE_EFFECT_APPLY_RANGE_TYPE,
	DBO_SKILL_PASSIVE_EFFECT_APPLY_AREA_SIZE_UP,
	DBO_SKILL_PASSIVE_EFFECT_USE_RANGE_MAX_UP,

	DBO_SKILL_PASSIVE_EFFECT_COUNT,

	DBO_SKILL_PASSIVE_EFFECT_INVALID = 0xFFui8,

	DBO_SKILL_PASSIVE_EFFECT_FIRST = DBO_SKILL_PASSIVE_EFFECT_CASTING_TIME_DOWN,
	DBO_SKILL_PASSIVE_EFFECT_LAST = DBO_SKILL_PASSIVE_EFFECT_COUNT - 1,
};

//-----------------------------------------------------------------------------------
// 스킬 이펙트 코드 정의
//-----------------------------------------------------------------------------------
#ifdef DEF_SYSTEM_EFFECT_CODE
	#undef DEF_SYSTEM_EFFECT_CODE
#endif
#define DEF_SYSTEM_EFFECT_CODE(c, can_cast_when_being_interrupted) c,

enum eSYSTEM_EFFECT_CODE
{
	PASSIVE_MAX_LP_UP,
	PASSIVE_MAX_EP_UP,
	PASSIVE_MAX_RP_DOWN,
	PASSIVE_PHYSICAL_OFFENCE_UP,
	PASSIVE_ENERGY_OFFENCE_UP,
	PASSIVE_PHYSICAL_DEFENCE_UP,
	PASSIVE_ENERGY_DEFENCE_UP,
	PASSIVE_STR_UP,
	PASSIVE_CON_UP,
	PASSIVE_FOC_UP,
	PASSIVE_DEX_UP,
	PASSIVE_SOL_UP,
	PASSIVE_ENG_UP,
	PASSIVE_DASH,
	PASSIVE_HOVERING,
	PASSIVE_LP_REGENERATION,
	PASSIVE_EP_REGENERATION,
	PASSIVE_ATTACK_RATE_UP,
	PASSIVE_DODGE_RATE_UP,
	PASSIVE_BLOCK_RATE_UP,
	PASSIVE_CURSE_SUCCESS_UP,
	PASSIVE_CURSE_TOLERANCE_UP,
	PASSIVE_PHYSICAL_CRITICAL_UP,
	PASSIVE_ENERGY_CRITICAL_UP,
	PASSIVE_RP_CHARGE_SPEED,
	PASSIVE_MOVE_SPEED,
	PASSIVE_ATTACK_SPEED_UP,
	PASSIVE_SKILL_CASTING_TIME_DOWN,
	PASSIVE_SKILL_COOL_TIME_DOWN,
	PASSIVE_CHARGE,
	PASSIVE_BLOCK_MODE,
	PASSIVE_GUARD_COUNTERATTACK,
	PASSIVE_DOT_VALUE_UP_ALL,
	PASSIVE_DOT_TIME_UP_ALL,
	PASSIVE_SKILL_EFFECT_VALUE_UP,
	PASSIVE_SKILL_KEEP_TIME_UP,
	PASSIVE_REQUIRE_EP_DOWN,
	PASSIVE_CHANGE_APPLY_RANGE,
	PASSIVE_APPLY_AREA_SIZE_UP,
	PASSIVE_USE_RANGE_UP,

	PASSIVE_MASTERY,
	PASSIVE_AIR_MASTERY,

	ACTIVE_DIRECT_DAMAGE,
	ACTIVE_BACKSTAB,
	ACTIVE_WARP_BACK_ATTACK,
	ACTIVE_THROUGH_ATTACK,
	ACTIVE_CRITICAL_ATTACK,
	ACTIVE_EXPLOSION_BLEED,
	ACTIVE_EXPLOSION_POISON,
	ACTIVE_EXPLOSION_STOMACHACHE,
	ACTIVE_EXPLOSION_BURN,
	ACTIVE_EXPLOSION_ALL_DOT,


	ACTIVE_BLEED,
	ACTIVE_POISON,
	ACTIVE_STOMACHACHE,
	ACTIVE_BURN,


	ACTIVE_DIRECT_HEAL,
	ACTIVE_DIRECT_EP_HEAL,


	ACTIVE_HEAL_OVER_TIME,
	ACTIVE_EP_OVER_TIME,


	ACTIVE_TELEPORT_BIND,
	ACTIVE_INVITE,
	ACTIVE_VISIT,
	ACTIVE_POISON_CURE,
	ACTIVE_STOMACHACHE_CURE,
	ACTIVE_PARALYZE_CURE,
	ACTIVE_CURSE_DEBUFF,
	ACTIVE_SUPER_SAIYAN,
	ACTIVE_PURE_MAJIN,
	ACTIVE_SUMMON,
	ACTIVE_EP_UP,
	ACTIVE_RP_UP,
	ACTIVE_RESCUE,
	ACTIVE_QUEST_TRIGGER,
	ACTIVE_OBJECT_TRIGGER,
	ACTIVE_GAMBLE_ITEM,
	ACTIVE_KAIOKEN,
	ACTIVE_VEHICLE,
	ACTIVE_WARP,
	ACTIVE_CLEAR_TARGET,
	ACTIVE_RECIPE_UPDATE,
	ACTIVE_CREATE_HOIPOI_MIX_MACHINE,
	ACTIVE_CREATE_HOIPOI_HOUSE,
	ACTIVE_MONSTER_TRANSFORM,
	ACTIVE_GREAT_NAMEK,
	ACTIVE_SCRIPT_SIGNAL_SPS,
	ACTIVE_SCRIPT_SIGNAL_TQS,
	ACTIVE_SCRIPT_SIGNAL_WPS,
	ACTIVE_SCRIPT_SIGNAL_AIS,
	ACTIVE_SCRIPT_EXECUTE_WPS_LOC,
	ACTIVE_SHIFT_SEAL_STATE,
	ACTIVE_TELEPORT_DOJO,
	ACTIVE_SELF_RESCUE,
	ACTIVE_CALL_PARTY_MEMBER,
	ACTIVE_BLEED_CURE,
	ACTIVE_BURN_CURE,
	ACTIVE_SMOKE_MOVE,
	ACTIVE_MIND_CONQUEST,
	ACTIVE_BODY_CONQUEST,
	ACTIVE_CHANGE_CONQUEST,
	ACTIVE_CURSE_EAT,


	ACTIVE_BIG_MONKEY,
	ACTIVE_FUSION,
	ACTIVE_TRANSFORM,
	ACTIVE_MAX_LP_UP,
	ACTIVE_MAX_EP_UP,
	ACTIVE_MAX_RP_UP,
	ACTIVE_PHYSICAL_OFFENCE_UP,
	ACTIVE_ENERGY_OFFENCE_UP,
	ACTIVE_PHYSICAL_DEFENCE_UP,
	ACTIVE_ENERGY_DEFENCE_UP,
	ACTIVE_STR_UP,
	ACTIVE_CON_UP,
	ACTIVE_FOC_UP,
	ACTIVE_DEX_UP,
	ACTIVE_SOL_UP,
	ACTIVE_ENG_UP,
	ACTIVE_MOVE_SPEED_UP,
	ACTIVE_ATTACK_SPEED_UP,
	ACTIVE_ATTACK_RATE_UP,
	ACTIVE_DODGE_RATE_UP,
	ACTIVE_BLOCK_RATE_UP,
	ACTIVE_HONEST_DEFENCE_UP,
	ACTIVE_STRANGE_DEFENCE_UP,
	ACTIVE_WILD_DEFENCE_UP,
	ACTIVE_ELEGANCE_DEFENCE_UP,
	ACTIVE_FUNNY_DEFENCE_UP,
	ACTIVE_ENERGY_REFLECTION,
	ACTIVE_LP_REGENERATION,
	ACTIVE_EP_REGENERATION,
	ACTIVE_RP_CHARGE_SPEED,
	ACTIVE_CURSE_SUCCESS,
	ACTIVE_CURSE_TOLERANCE,
	ACTIVE_PHYSICAL_CRITICAL,
	ACTIVE_ENERGY_CRITICAL,
	ACTIVE_SKILL_CASTING_TIME_DOWN,
	ACTIVE_SKILL_COOL_TIME_DOWN,
	ACTIVE_ITEM_BREAK_RATE_DOWN,
	ACTIVE_BARRIER,
	ACTIVE_PARALYZE_TOLERANCE_UP,
	ACTIVE_TERROR_TOLERANCE_UP,
	ACTIVE_CONFUSE_TOLERANCE_UP,
	ACTIVE_STONE_TOLERANCE_UP,
	ACTIVE_CANDY_TOLERANCE_UP,
	ACTIVE_PARALYZE_KEEPTIME_DOWN,
	ACTIVE_TERROR_KEEPTIME_DOWN,
	ACTIVE_CONFUSE_KEEPTIME_DOWN,
	ACTIVE_STONE_KEEPTIME_DOWN,
	ACTIVE_CANDY_KEEPTIME_DOWN,
	ACTIVE_BLEEDING_KEEPTIME_DOWN,
	ACTIVE_POISON_KEEPTIME_DOWN,
	ACTIVE_STOMACHACHE_KEEPTIME_DOWN,
	ACTIVE_CRITICAL_BLOCK_UP,
	ACTIVE_NORMAL_SKILL_BLOCK_UP,
	ACTIVE_CURSE_SKILL_BLOCK_UP,
	ACTIVE_KNOCKDOWN_ATTACK_BLOCK_UP,
	ACTIVE_HTB_SKILL_BLOCK_UP,
	ACTIVE_SIT_DOWN_LP_REGENERATION_UP,
	ACTIVE_SIT_DOWN_EP_REGENERATION_UP,
	ACTIVE_PHYSICAL_CRITICAL_DAMAGE_UP,
	ACTIVE_ENERGY_CRITICAL_DAMAGE_UP,
	ACTIVE_ITEM_UPGRADE_RATE_UP,
	ACTIVE_SPINNING_ATTACK,
	ACTIVE_ATTACK_RANGE_UP,
	ACTIVE_HIDE_KI,
	ACTIVE_HIDE,
	ACTIVE_FAKE_DEATH,
	ACTIVE_CANT_BE_TARGETTED,
	ACTIVE_BATTLE_ATTRIBUTE_UP,
	ACTIVE_PHYSICAL_REFLECTION,
	ACTIVE_PERFECT_GUARD,
	ACTIVE_LP_RECOVERY,
	ACTIVE_EP_RECOVERY,
	ACTIVE_HONEST_OFFENCE_UP,
	ACTIVE_STRANGE_OFFENCE_UP,
	ACTIVE_WILD_OFFENCE_UP,
	ACTIVE_ELEGANCE_OFFENCE_UP,
	ACTIVE_FUNNY_OFFENCE_UP,
	ACTIVE_LP_RECOVERY_IN_PERCENT,
	ACTIVE_EP_RECOVERY_IN_PERCENT,
	ACTIVE_STOMACHACHE_DEFENCE,
	ACTIVE_POSION_DEFENCE,
	ACTIVE_BLEED_DEFENCE,
	ACTIVE_BURN_DEFENCE,
	ACTIVE_BATTLE_LP_UP,
	ACTIVE_BATTLE_EP_UP,
	ACTIVE_ALL_OFFENCE_UP,
	ACTIVE_ALL_DEFENCE_UP,
	ACTIVE_LP_AUTO_RECOVER,
	ACTIVE_EP_AUTO_RECOVER,
	ACTIVE_RABIES,
	ACTIVE_DRUNK,
	ACTIVE_VIABILITY,
	ACTIVE_MIND_IMMUNITY,
	ACTIVE_BODY_IMMUNITY,
	ACTIVE_CHANGE_IMMUNITY,
	ACTIVE_SKILL_AGGRO_UP,
	ACTIVE_SKILL_AGGRO_DOWN,
	ACTIVE_DH_POWER_UP,
	ACTIVE_HOT_POWER_UP,

	ACTIVE_ROLLING_ATTACK,
	ACTIVE_REFLECT_CURSE,
	ACTIVE_ABSORB_CURSE,
	ACTIVE_WEIGHT_LIMIT_UP,
	ACTIVE_EXCITATION_MALE,
	ACTIVE_INVINCIBLE,
	ACTIVE_SKILL_AGGRO_UP_IN_PERCENT,
	ACTIVE_SKILL_AGGRO_DOWN_IN_PERCENT,
	ACTIVE_DH_POWER_UP_IN_PERCENT,
	ACTIVE_HOT_POWER_UP_IN_PERCENT,
	ACTIVE_EXCITATION_FEMALE,

	ACTIVE_AIR_MOVE,
	ACTIVE_AIR_DASH,
	ACTIVE_AIR_ACCEL,
	ACTIVE_AIR_MOVE_DASH_ACCEL,
	ACTIVE_AIR_QUICK,
	ACTIVE_MAX_AP_UP,
	ACTIVE_AP_REGENERATION,


	ACTIVE_EP_DOWN,
	ACTIVE_RP_DOWN,
	ACTIVE_BLESS_DEBUFF,
	ACTIVE_LP_STEAL,
	ACTIVE_EP_STEAL,
	ACTIVE_PULL,
	ACTIVE_MAKE_LOWEST_AGGRO,
	ACTIVE_AGGRO_DOWN,
	ACTIVE_AGGRO_UP,
	ACTIVE_YELL,
	ACTIVE_EXPLOSION_POWER,
	ACTIVE_ARSON,
	ACTIVE_BLESS_DEBUFF_MULTI,


	ACTIVE_TAUNT,
	ACTIVE_PARALYZE,
	ACTIVE_CONFUSE,
	ACTIVE_TERROR,
	ACTIVE_STUN,
	ACTIVE_SLEEP,
	ACTIVE_STONE,
	ACTIVE_CANDY,
	ACTIVE_MAX_LP_DOWN,
	ACTIVE_MAX_EP_DOWN,
	ACTIVE_MAX_RP_DOWN,
	ACTIVE_PHYSICAL_OFFENCE_DOWN,
	ACTIVE_ENERGY_OFFENCE_DOWN,
	ACTIVE_PHYSICAL_DEFENCE_DOWN,
	ACTIVE_ENERGY_DEFENCE_DOWN,
	ACTIVE_STR_DOWN,
	ACTIVE_CON_DOWN,
	ACTIVE_FOC_DOWN,
	ACTIVE_DEX_DOWN,
	ACTIVE_SOL_DOWN,
	ACTIVE_ENG_DOWN,
	ACTIVE_MOVE_SPEED_DOWN,
	ACTIVE_ATTACK_SPEED_DOWN,
	ACTIVE_ATTACK_RATE_DOWN,
	ACTIVE_DODGE_RATE_DOWN,
	ACTIVE_BLOCK_RATE_DOWN,
	ACTIVE_HONEST_DEFENCE_DOWN,
	ACTIVE_STRANGE_DEFENCE_DOWN,
	ACTIVE_WILD_DEFENCE_DOWN,
	ACTIVE_ELEGANCE_DEFENCE_DOWN,
	ACTIVE_FUNNY_DEFENCE_DOWN,
	ACTIVE_SKILL_CASTING_TIME_UP,
	ACTIVE_SKILL_COOL_TIME_UP,
	ACTIVE_ATTACK_RANGE_DOWN,
	ACTIVE_TIED_UP,
	ACTIVE_BAN_CHARGE,
	ACTIVE_FREEZE,
	ACTIVE_LP_STEAL_OVER_TIME,
	ACTIVE_EP_STEAL_OVER_TIME,
	ACTIVE_BATTLE_ATTRIBUTE_DOWN,
	ACTIVE_WARP_STUN,
	ACTIVE_TAIYOU_KEN,
	ACTIVE_BATTLE_INABILITY,
	ACTIVE_SKILL_LP_DAMAGE,
	ACTIVE_SKILL_EP_DAMAGE,
	ACTIVE_SKILL_INABILITY,
	ACTIVE_ALL_OFFENCE_DOWN,
	ACTIVE_ALL_DEFENCE_DOWN,
	ACTIVE_WOUND,
	ACTIVE_WEIGHT_LIMIT_DOWN,



	ACTIVE_TELEPORT,
	ACTIVE_SPECIAL_UPGRADE,
	ACTIVE_PARTY_POPO,
	ACTIVE_SKILL_RESET,
	ACTIVE_CHARACTER_RENAME,
	ACTIVE_YUHA_RENAME,
	ACTIVE_SAIBAIMAN_SUMMON,
	ACTIVE_SEX_LOOKS_CHANGE,
	ACTIVE_CRESCENT_POPO,
	ACTIVE_SKILL_RESET_PLUS,
	ACTIVE_EXP_BOOSTER,
	ACTIVE_MASCOT_REGIST,
	ACTIVE_MASCOT_SATIETY_UP,
	ACTIVE_MASCOT_RING_QUEST_SUPPORT,
	ACTIVE_SKILL_RESET_ONE,
	ACTIVE_TMQ_LIMIT_COUNT_PLUS,
	ACTIVE_ADVANCED_RESCUE,
	ACTIVE_REVIVAL_AFTEREFFECT,
	ACTIVE_REVIVAL_AFTEREFFECT_PCBANG,
	ACTIVE_REVIVAL_AFTEREFFECT_CURE_MINOR,
	ACTIVE_REVIVAL_AFTEREFFECT_CURE_MAJOR,
	ACTIVE_EVENT_COIN_PLUS,
	ACTIVE_SET_LEVEL,
	ACTIVE_LEARN_SKILL,
	ACTIVE_WAGU_COIN_PLUS,
	ACTIVE_CHAR_TITLE,
	ACTIVE_CHILD_ADULT_TRANSFORM,
	ACTIVE_MASCOT_VP_RECOVERY,
	ACTIVE_MASCOT_VP_AUTO_RECOVERY,
	ACTIVE_MASCOT_EXP_AUTO_PORTION,
	ACTIVE_MASCOT_SKILL_GRADEUP,
	ACTIVE_AUTO_LOOTING,
	ACTIVE_NPC_TELEPORT,
	ACTIVE_PARTY_SUMMON,
	ACTIVE_GUILD_SUMMON,
	PASSIVE_SELF_RESCUE,
	PASSIVE_INFINITE_DASH,
	ACTIVE_REMOTE_SELL,
	ACTIVE_REMOTE_WAREHOUSE,

	ACTIVE_SCOUTER_CHECK_DRAGONBALL,
	ACTIVE_SCOUTER_CHECK_ABILITY_ATTACK,
	ACTIVE_SCOUTER_CHECK_MONSTER,
	ACTIVE_SCOUTER_CHECK_EQUIPMENT,

	MAX_SYSTEM_EFFECT_CODE,

	INVALID_SYSTEM_EFFECT_CODE = 0xFFFFFFFF
};
//-----------------------------------------------------------------------------------



//-----------------------------------------------------------------------------------
// 스킬 관련 정의
//-----------------------------------------------------------------------------------
const unsigned int MAX_PC_HAVE_SKILL = 120;

const unsigned int MAX_NPC_HAVE_SKILL = 7;

const unsigned int MAX_BLESS_BUFF_CHARACTER_HAS = 8;

const unsigned int MAX_CURSE_BUFF_CHARACTER_HAS = 8;

const unsigned int DBO_MAX_BUFF_CHARACTER_HAS = MAX_BLESS_BUFF_CHARACTER_HAS + MAX_CURSE_BUFF_CHARACTER_HAS;

const unsigned int MAX_EFFECT_IN_SKILL = 2;

const int SYSTEM_EFFECT_1 = 0;

const int SYSTEM_EFFECT_2 = 1;

const unsigned int EFFECT_APPLY_INTERVAL = 2 * 1000;		// in millisecs.

const unsigned int MAX_NUMBER_OF_SKILL_TARGET = 8;

const BYTE INVALID_BUFF_GROUP = 0xFF;

const float DBO_BACKSTAB_DAMAGE_BONUS_IN_PERCENT = 50.0f;		// in percent

const unsigned int DBO_MAX_RP_BONUS_COUNT_PER_SKILL = 6;

const float DBO_DEFAULT_BLOCK_MODE_SUCCESS_RATE = 70.0f;		// in percent

const float DBO_MAX_BLOCK_MODE_SUCCESS_RATE = 70.0f;		// in percent

const float DBO_MAX_CRITICAL_BLOCK_SUCCESS_RATE = 100.0f;		// in percent

const float DBO_CONFUSE_SCAN_DISTANCE_PC = 20.0f;				// in meters.

const float DBO_MAX_TERROR_MOVEMENT_DISTANCE = 30.0f;			// in meters.

const float DBO_SYSTEM_EFFECT_PULL_DISTANCE = 1.0f;				// in meters.

const DWORD DBO_MIN_POWER_LEVEL_WHEN_HIDING_KI = 1;

const float DBO_KEEPING_EFFECT_VALID_DISTANCE_BUFFER = 10.0f;		// in meters.

const float DBO_STRIKE_RUSH_MOVEMENT_SPEED = 60.0f;					// in m/s
//-----------------------------------------------------------------------------------


//-----------------------------------------------------------------------------------
// HTB 관련 정의
//-----------------------------------------------------------------------------------
const DWORD			HTB_MAX_PC_HAVE_HTB_SKILL				= 30; // PC가 가지는 HTB 스킬의 최대 개수
const DWORD			HTB_MAX_SKILL_COUNT_IN_SET				= 10; // 한 개의 HTB skill set에 포함될 수 있는 스킬의 최대 개수
const BYTE			DBO_HTB_PREREQUISITE_RP_BALL				= 1;		// HTB를 쓰기 위해 필요한 최소 RP 구슬
//-----------------------------------------------------------------------------------



//-----------------------------------------------------------------------------------
//
//-----------------------------------------------------------------------------------
const char *		NtlGetSystemEffectString(DWORD dwSystemEffectCode);
const bool			NtlCanCastWhenBeingInterrupted(eSYSTEM_EFFECT_CODE eSystemEffectCode);
bool				Dbo_IsForBlessBuff(BYTE byActiveEffectType);
bool				Dbo_IsForCurseBuff(BYTE byActiveEffectType);
bool				Dbo_IsHarmfulEffectType(BYTE byActiveEffectType);
//-----------------------------------------------------------------------------------



// 스킬 관련 packet structure
#pragma pack(1)


struct sSKILL_DATA
{	// 캐릭터의 스킬 저장 정보
	BYTE				bySlot;
	TBLIDX				skillId;
	int					nRemainSec;
	int					nExp;
	BYTE				byRpBonusType;
	bool				bIsRpBonusAuto;
};

struct sBUFF_DATA
{
	TBLIDX				sourceTblidx;
	BYTE				bySourceType;		// eDBO_OBJECT_SOURCE
	DWORD				dwInitialDuration;
	DWORD				dwTimeRemaining;		// in Millisecs.
	int					nArgument1;
	int					nArgument2;
	float				fEffectValue1;
	float				fEffectValue2;
	BYTE				byBuffGroup;		//
};


struct sPET_BUFF_DATA
{
	BYTE				byAvatarType;		// eDBO_AVATAR_TYPE
	BYTE				bySourceType;		// eDBO_OBJECT_SOURCE
	TBLIDX				sourceTblidx;
	DWORD				dwInitialDuration;
	DWORD				dwTimeRemaining;		// in Millisecs.
	int					nArgument1;
	int					nArgument2;
	float				fEffectValue1;
	float				fEffectValue2;
};


// HTB 스킬 데이타 ( DB 로딩용 )
struct sHTB_SKILL_DATA
{
	TBLIDX			skillId; // HTB Skill ID
	int				nSkillTime; // Remaining time(in millisecs.)
};


// 스킬 정보
struct sSKILL_INFO
{
	TBLIDX			tblidx; // 스킬 tblidx
	DWORD			dwTimeRemaining;		// in millisecs.
	int				nExp;
	BYTE			bySlotId;
	BYTE			byRpBonusType;			// eDBO_RP_BONUS_TYPE
	bool			bIsRpBonusAuto;
};


// 펫 스킬 정보
struct sSKILL_INFO_PET
{
	TBLIDX			tblidx; // 스킬 tblidx
	BYTE			bySlotIndex;
};


struct sBUFF_INFO
{
	DWORD	SourceTblidx;
	BYTE	bySourceType;			// eDBO_OBJECT_SOURCE
	DWORD	dwInitialDuration;
	DWORD	dwTimeRemaining;		// in millisecs.
	DWORD   IsActive;//

	WORD    EffectType;
	DWORD	InitialDuration; //time again
	DWORD	afEffectValue[2]; //Value 0 only
	DWORD	unk2;
	BYTE	unk3[5];

	WORD	EffectType2;
	DWORD	InitialDuration2;//time again
	DWORD	afEffectValue2[2];//Value 1 only
	BYTE    unk5[6];
	bool    unk6;
};


// HTB 스킬 데이타 ( 클라이언트 전달용 )
struct sHTB_SKILL_INFO
{
	TBLIDX			skillId; // HTB Skill ID
	BYTE			bySlotId;
	DWORD			dwTimeRemaining; // millisecs
};
// System Effect 결과
struct sDBO_SYSTEM_EFFECT_RESULT
{
	DWORD	eResultType;
	float	 Value1;
	float	 Value2;
	float	 Value3;
	float	 Value4;
	float	 Value5;
	float	 Value6;	
};

// SKILL 결과 값
struct sSKILL_RESULT
{
	HOBJECT			hTarget;
	BYTE			byAttackResult;		// eBATTLE_ATTACK_RESULT
	sDBO_SYSTEM_EFFECT_RESULT		effectResult[2];
	BYTE							byBlockedAction;		// eDBO_GUARD_TYPE
	DWORD	 unk1;
	sVECTOR3		vShift;
	sVECTOR3		vShift1;
};


// HTB 스킬 결과 값
struct sHTBSKILL_RESULT
{
	BYTE			byStep; // 현재 HTB 스텝
	sSKILL_RESULT	sSkillResult;
};


// Bot용 스킬 데이타 [2/11/2008 SGpro]
struct sSKILL_DATA_BOT
{	// 캐릭터의 스킬 저장 정보
	BYTE				bySlot;
	TBLIDX				skillId;
	int					nRemainSec;
};

// 스킬 정보 [2/11/2008 SGpro]
struct sSKILL_INFO_BOT
{
	TBLIDX			tblidx; // 스킬 tblidx
	DWORD			dwTimeRemaining; // in millisecs.
	BYTE			bySlotId;
};

// 스킬 AI 조건 정보 [2/15/2008 SGpro]
enum eSKILLPRIORITY
{	
	 SKILLPRIORITY_CALL = 0x00ui8		// 사용안함 [2/15/2008 SGpro]
	,SKILLPRIORITY_START				// 사용안함 [2/15/2008 SGpro]
	,SKILLPRIORITY_FAINTING				// 사용안함 [2/15/2008 SGpro]
	,SKILLPRIORITY_LP					// table의 lp보다 자신에 lp가 작고, cool time이 되고, table의 time보다 딜레이가 되었다면 스킬 발동 [10/29/2008 SGpro]
	,SKILLPRIORITY_GIVE					// table의 lp보다 파티원에 lp가 작고 , cool time이 되고, table의 time보다 딜레이가 되었다면 스킬 발동 [10/29/2008 SGpro]
	,SKILLPRIORITY_TIME					// table의 time과 cool time이 조건에 합당하면 스킬 발동 [10/29/2008 SGpro]
	,SKILLPRIORITY_RINGRANGE			// 도너츠 영역에 적이 있으면 스킬이 발동됨 [8/12/2008 SGpro]
	,SKILLPRIORITY_ONLYLP				// table의 lp 보다 자신에 lp가 낮고 cool time이 되면 스킬발동, 단 한번만 발동( 에너지가 찼다가 다시 줄어들면 다시 또 발동 ) [10/29/2008 SGpro]
};

struct sDBO_UPDATED_SKILL_DATA
{
	BYTE			bySkillPassiveEffect;		// eDBO_SKILL_PASSIVE_EFFECT
	union
	{
		// DBO_SKILL_PASSIVE_EFFECT_CASTING_TIME_DOWN
		float		fCasting_Time;

		// DBO_SKILL_PASSIVE_EFFECT_COOL_TIME_DOWN
		WORD		wCool_Time;

		// DBO_SKILL_PASSIVE_EFFECT_SYSTEM_EFFECT_VALUE_UP
		float		fSkill_Effect_Value[MAX_EFFECT_IN_SKILL];

		// DBO_SKILL_PASSIVE_EFFECT_KEEP_TIME_UP
		WORD		wKeep_Time;

		// DBO_SKILL_PASSIVE_EFFECT_REQUIRED_EP_DOWN
		WORD		wRequire_EP;

		// DBO_SKILL_PASSIVE_EFFECT_APPLY_RANGE_TYPE
		BYTE		byApply_Range;

		// DBO_SKILL_PASSIVE_EFFECT_APPLY_AREA_SIZE_UP
		struct
		{
			BYTE	byApply_Area_Size_1;
			BYTE	byApply_Area_Size_2;
		};

		// DBO_SKILL_PASSIVE_EFFECT_USE_RANGE_MAX_UP
		BYTE		byUse_Range_Max;
	};
};

DWORD Dbo_GetLevelUpGainSP( BYTE byLevel, BYTE byLevelDiff=1 );
DWORD Dbo_GetLevelSP( BYTE byLevel );

#pragma pack()