#pragma once

#define NTL_SPAWN_ATTACK_DISTANCE		(2.6f)
#define NTL_GIVE_UP_BATTLE_MODE_DISTANCE		(19.6f)
#define NTL_PLAYER_ATTACK_DELAY_IN_MILLISECS		(1500)
#define NTL_PLAYER_CRITICALATTACK_DELAY_IN_MILLISECS (4000)
#define NTL_MOB_ATTACK_DELAY_IN_MILLISECS		(3000)