#pragma once

enum ENtlSex
{
	NTL_SEX_NONE = 0,

	NTL_SEX_NEUTER,
	NTL_SEX_MALE,
	NTL_SEX_FEMALE,

	NTL_SEX_FIRST = NTL_SEX_NEUTER,
	NTL_SEX_LAST = NTL_SEX_FEMALE
};

enum ENtlSpawnStatus
{
	NTL_SPAWN_STATUS_NORMAL = 0x00000000,

	NTL_SPAWN_STATUS_DIE = 0x00000001,
	
	NTL_SPAWN_STATUS_UNKNOWN = 0xFFFFFFFF,

	NTL_SPAWN_STATUS_FIRST = NTL_SPAWN_STATUS_NORMAL,
	NTL_SPAWN_STATUS_LAST = NTL_SPAWN_STATUS_DIE
};