#pragma once

#define NTL_NUMBER_OF_CAPSULE_SLOT_IN_PLAYER_INVENTORY		(5)
#define NTL_MAX_NUMBER_OF_SLOT_IN_BAG		(16)
#define NTL_MAX_NUMBER_IN_STACK		(20)

enum ENtlEquipSlot
{
	NTL_EQUIP_SLOT_LEFT_EAR = 0,
	NTL_EQUIP_SLOT_RIGHT_EAR,
	NTL_EQUIP_SLOT_NECKLACE,
	NTL_EQUIP_SLOT_FINGER_1,
	NTL_EQUIP_SLOT_FINGER_2,
	NTL_EQUIP_SLOT_UPPER_BODY,
	NTL_EQUIP_SLOT_LOWER_BODY,
	NTL_EQUIP_SLOT_FOOT,
	NTL_EQUIP_SLOT_LEFT_HAND,
	NTL_EQUIP_SLOT_RIGHT_HAND,
	NTL_EQUIP_SLOT_SCOUTER,

	NTL_EQUIP_SLOT_NONE = 0xFFFFFFFF,

	NTL_EQUIP_SLOT_ARMOR_FIRST = NTL_EQUIP_SLOT_LEFT_EAR,
	NTL_EQUIP_SLOT_ARMOR_LAST = NTL_EQUIP_SLOT_FOOT,

	NTL_EQUIP_SLOT_FIRST = NTL_EQUIP_SLOT_LEFT_EAR,
	NTL_EQUIP_SLOT_LAST = NTL_EQUIP_SLOT_SCOUTER,

	NTL_EQUIP_SLOT_TOTAL_NUMBER_OF_SLOT = (NTL_EQUIP_SLOT_LAST + 1)
};